let placesToVisit: string[] = ["London","America","Korea","Canada","Malaysia"];
console.log("Orignal order:", placesToVisit);
console.log("Alphabetical order:", [...placesToVisit].sort());
console.log("Orignal order after sorting:", placesToVisit);
console.log("Reverse alphabetical order:", [...placesToVisit].sort().reverse());
console.log("Orignal order after reverse sorting:", placesToVisit);
placesToVisit.reverse();
console.log("Reversed order:",placesToVisit);
placesToVisit.reverse();
console.log("Back to Orignal order:",placesToVisit);
placesToVisit.sort();
console.log("Sorted in alphabetical order:",placesToVisit);
placesToVisit.sort((a,b) => b.localeCompare(a));
console.log("Sorted in reverse alphabetical order:",placesToVisit);